# Generated by Django 4.2.3 on 2023-08-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteVisitors',
            new_name='SiteVisitor',
        ),
    ]
