# Generated by Django 4.2.3 on 2023-08-02 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0002_rename_sitevisitors_sitevisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitor',
            name='visitor_bowser_platform',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitevisitor',
            name='visitor_date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitevisitor',
            name='visitor_user_agent',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitevisitor',
            name='visitor_bowser',
            field=models.CharField(max_length=255),
        ),
    ]
