# Generated by Django 4.2.3 on 2023-08-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0003_sitevisitor_visitor_bowser_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FusionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_favicon', models.ImageField(upload_to='static/img/site/img')),
                ('site_icon', models.ImageField(upload_to='static/img/site/img')),
                ('site_name', models.CharField(max_length=255)),
                ('site_status', models.CharField(max_length=50)),
                ('site_description', models.TextField(max_length=255)),
                ('site_author', models.CharField(max_length=100)),
                ('site_keyword', models.TextField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
