# Generated by Django 4.2.3 on 2023-08-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0005_alter_fusionconfiguration_site_favicon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fusionconfiguration',
            options={'ordering': ['-date_added'], 'verbose_name': 'Configuration', 'verbose_name_plural': 'Configurations'},
        ),
        migrations.AlterModelOptions(
            name='sitevisitor',
            options={'ordering': ['-visitor_date_added'], 'verbose_name': 'Visitor', 'verbose_name_plural': 'Visitors'},
        ),
    ]
